/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_annotion_ruiyi_jnifile_JniHelper */

#ifndef _Included_com_annotion_ruiyi_jnifile_JniHelper
#define _Included_com_annotion_ruiyi_jnifile_JniHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_annotion_ruiyi_jnifile_JniHelper
 * Method:    SaveString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_annotion_ruiyi_jnifile_JniHelper_SaveString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
